import "@/app/ui/globals.css";

import { Metadata } from "next";
import { HeaderLoBram } from "@/app/ui/headerLoBram";
import { overlock, quattrocento } from "@/app/ui/fonts";
import Footer from "@/app/ui/footer";
import { fetchPagines } from "./lib/data";

// Tipus per a representar una pàgina.
type Pagina = {
  _id: string;
  _rev: string;
  _type: string;
  href: string;
  key: string;
  ordre: number;
  title: { ca: string };
  _createdAt: string;
  _updatedAt: string;
};

export const metadata: Metadata = {
  title: "Lo Bram",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // load structured data from builder.io named "main-links" of type main-links
  const pagines = await fetchPagines();
  // Construeix l'objecte de links a partir de les pàgines.
  const links = pagines.reduce((acc: any, pagina: Pagina) => {
    const key = pagina.key.toLowerCase().replace(/\s+/g, ""); // Convertir la clau en un identificador vàlid.
    acc[key] = {
      title: pagina.title.ca,
      href: pagina.href,
    };
    return acc;
  }, {} as Record<string, { title: string; href: string }>);

  return (
    <html lang="ca" className="light">
      <head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
      </head>

      <body className={`${quattrocento.className} bg-blue-50 text-gray-700`}>
        <HeaderLoBram links={Object.values(links)} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
