import "@/app/ui/globals.css";

import { Metadata } from "next";
import { Header } from "@/app/ui/header";
import { overlock, quattrocento } from "@/app/ui/fonts";
import Footer from "@/app/ui/footer";

export const metadata: Metadata = {
  title: "Lo Bram",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // load structured data from builder.io named "main-links" of type main-links
  const links = {
    home: {
      title: "Inici",
      href: "/",
    },
    grups: {
      title: "Grups de treball",
      href: "/grups_treball",
    },
    dances: {
      title: "Dances sagrades",
      href: "/dances",
    },
    lEspai: {
      title: "L'Espai",
      href: "/lespai",
    },
    contacte: {
      title: "Contacte",
      href: "/contacte",
    },
  };

  return (
    <html lang="ca" className="light">
      <head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
      </head>

      <body className={`${quattrocento.className} bg-blue-50 text-gray-700`}>
        <Header links={Object.values(links)} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
