/**
 * This code was generated by Builder.io.
 */

import Image from "next/image";

type ComponentProps = {
  imageUrl: string;
  altText: string;
  headerText: string;
  paragraphText: string[];
};

export default function Historia2(props: ComponentProps) {
  const { imageUrl, altText, headerText, paragraphText } = props;

  return (
    <div className="flex flex-col relative shrink-0 box-border items-stretch w-full mx-auto">
      <header className="flex max-md:flex-col max-md:items-stretch max-md:gap-0">
        <div className="md:w-1/2 ">
          <div
            className="flex flex-col items-stretch relative w-full"
            style={{
              height: "60vh",
            }}
          >
            <Image
              loading="lazy"
              src={imageUrl}
              alt={altText}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </div>
        <div className="flex flex-col items-stretch w-6/12  max-md:w-full max-md:ml-0">
          <div
            className="items-stretch relative shrink-0 box-border h-auto text-left text-3xl font-medium mt-5"
            aria-label="Company values"
            role="heading"
          >
            <p>{headerText}</p>
          </div>
          <div className="items-stretch shrink-0 relative text-center leading-8 h-auto mt-1.5 pr-2 max-sm:text-sm">
            {paragraphText.map((paragraph, index) => (
              <p key={index}>{paragraph}</p>
            ))}
          </div>
        </div>
      </header>
    </div>
  );
}
